import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';

const TEACHER_EMAIL = process.env.TEACHER_EMAIL;

const MODULE = {
  title: 'Crypto & Taxes',
  emoji: '💸',
  description: 'How the IRS treats cryptocurrency — taxable events, capital gains, cost basis methods, Form 1099-DA, tax-loss harvesting, mining and staking income, and the software tools that make reporting manageable.',
  order_index: 15,
};

const LESSONS = [

  // ═══════════════════════════════════════════════════════
  // 1. IS CRYPTO TAXABLE?
  // ═══════════════════════════════════════════════════════
  {
    title: 'Is Crypto Taxable? The IRS Says Yes',
    emoji: '🏛️',
    description: 'The IRS treats cryptocurrency as property, not currency. That one fact changes everything about how you report it. This lesson explains the foundational rules every crypto holder needs to know.',
    order_index: 1,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '🏛️ Cryptocurrency = Property Under US Tax Law' } },
      { block_type: 'text', content: { text: 'In 2014, the IRS issued **Notice 2014-21**, establishing the foundational rule that governs crypto taxes in the US:\n\n> **Cryptocurrency is treated as PROPERTY for federal tax purposes — not as currency.**\n\nThis one decision has enormous consequences:\n\n- When you sell crypto for a profit → that profit is a **capital gain** (taxable)\n- When you sell crypto at a loss → that loss is a **capital loss** (deductible)\n- When you receive crypto as payment for work → that crypto is **income** (taxable at full rates)\n- When you receive free crypto (airdrops, forks) → that may also be **income**\n\n**The key question every transaction requires:** "What was my cost basis when I acquired this crypto, and what was its fair market value when I disposed of it?"\n\n**Disposal** = selling, trading, spending, or transferring crypto in exchange for something of value.' } },

      { block_type: 'heading', content: { text: '📋 What MUST Be Reported' } },
      { block_type: 'text', content: { text: 'The IRS added a question to **Form 1040** (the main US tax return) asking directly about crypto:\n\n```\n  At any time during [year], did you:\n  receive (as a reward, award, or payment for property\n  or services); or sell, exchange, gift, or otherwise\n  dispose of a digital asset (or a financial interest\n  in a digital asset)?\n  \n  ☐ Yes  ☐ No\n```\n\n**Answer YES if you:**\n- Sold crypto for cash or another crypto\n- Traded one cryptocurrency for another\n- Spent crypto to buy goods or services\n- Received crypto as payment for work\n- Received mining or staking rewards\n- Received an airdrop\n\n**Answer NO if you ONLY:**\n- Bought crypto with US dollars and held it (no sale/trade)\n- Transferred crypto between your own wallets\n- Received crypto as a gift (and did not sell it)\n\n**Important:** Answering NO when you should have answered YES is a federal crime. The IRS has been aggressively pursuing crypto tax compliance since 2019.' } },

      { block_type: 'heading', content: { text: '⚠️ The IRS Has Been Watching' } },
      { block_type: 'text', content: { text: '**2019:** The IRS sent warning letters to 10,000 crypto holders who may have underreported gains.\n\n**2021:** Infrastructure Investment and Jobs Act expanded broker reporting requirements to include crypto — exchanges must now report customer transactions.\n\n**2023:** IRS announced **Form 1099-DA** — a new form specifically for digital assets, required from crypto exchanges starting in 2025 (for tax year 2025 onward).\n\n**Chain analysis:** The IRS uses blockchain analysis firms like Chainalysis to trace transactions. The public nature of blockchains means the IRS can see every transaction on Ethereum, Bitcoin, and most other chains — the only thing it may not immediately know is who controls a wallet address.\n\n**The exchange link:** When you buy on Coinbase with your Social Security number and send to a self-custody wallet, the IRS has the starting point. Blockchain analysis connects the rest.\n\n**Bottom line:** Crypto is NOT anonymous to the IRS for most users. Accurate reporting is both a legal requirement and a practical necessity.' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=d8kGs_UNBWU', title: 'Crypto Taxes Explained For Beginners', description: 'A clear introduction to how the IRS treats cryptocurrency as property, what counts as a taxable event, and the basics of crypto capital gains tax.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/crypto-taxes-usa-guide/', title: 'Crypto Taxes USA Guide — CoinDesk', description: 'CoinDesk\'s comprehensive guide to US cryptocurrency taxes — how the IRS classifies crypto, what must be reported, and key deadlines.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'How does the IRS classify cryptocurrency for tax purposes in the US?', explanation: 'The IRS issued Notice 2014-21 classifying cryptocurrency as PROPERTY, not currency. This means selling or trading crypto creates a capital gain or loss — just like selling a stock or piece of real estate.', options: [{ option_text: 'Property — like stocks or real estate, triggering capital gains rules', is_correct: true }, { option_text: 'Foreign currency — subject to currency exchange tax rules', is_correct: false }, { option_text: 'Commodity — taxed only when delivered physically', is_correct: false }, { option_text: 'Tax-exempt asset — crypto transactions are not reportable', is_correct: false }] },
      { question_text: 'Which of the following is a TAXABLE EVENT for cryptocurrency?', explanation: 'Trading one cryptocurrency for another (e.g., Bitcoin for Ethereum) is a taxable event — it\'s treated as selling Bitcoin and buying Ethereum. You must calculate the gain or loss based on your cost basis in the Bitcoin.', options: [{ option_text: 'Trading Bitcoin for Ethereum on an exchange', is_correct: true }, { option_text: 'Transferring Bitcoin from Coinbase to your Ledger hardware wallet', is_correct: false }, { option_text: 'Buying $500 of Bitcoin with US dollars', is_correct: false }, { option_text: 'Receiving Bitcoin as a gift from a family member', is_correct: false }] },
      { question_text: 'What question does the IRS include on Form 1040 about digital assets?', explanation: 'The IRS added a digital asset question directly to Form 1040 asking whether you received, sold, traded, or otherwise disposed of digital assets during the year. You must answer YES or NO — answering NO when you had taxable transactions is potentially a federal crime.', options: [{ option_text: 'Whether you received, sold, traded, or disposed of digital assets during the year', is_correct: true }, { option_text: 'The total dollar value of all crypto held at year-end', is_correct: false }, { option_text: 'Whether you used a licensed crypto exchange', is_correct: false }, { option_text: 'Whether your crypto wallet is registered with the government', is_correct: false }] },
      { question_text: 'What is Form 1099-DA?', explanation: 'Form 1099-DA is a new IRS form specifically for digital asset transactions. Starting with tax year 2025, crypto exchanges must issue this form to customers who have taxable events — similar to how brokers report stock trades on Form 1099-B.', options: [{ option_text: 'A new IRS form for digital asset transactions, required from exchanges starting tax year 2025', is_correct: true }, { option_text: 'A form to apply for a tax exemption on crypto gains', is_correct: false }, { option_text: 'A declaration that you hold crypto in a foreign account', is_correct: false }, { option_text: 'A form filed only by crypto miners', is_correct: false }] },
      { question_text: 'Buying Bitcoin with US dollars and holding it without selling — is this taxable?', explanation: 'No. Simply buying and holding crypto is NOT a taxable event. You only have a tax obligation when you DISPOSE of crypto — by selling, trading, spending, or giving it away. Unrealized gains are not taxed.', options: [{ option_text: 'No — buying and holding is not a taxable event; only disposal triggers taxes', is_correct: true }, { option_text: 'Yes — any increase in value is taxable each year, like property tax', is_correct: false }, { option_text: 'Yes — you must report the purchase amount on your tax return', is_correct: false }, { option_text: 'Only if you hold for more than one year — short-term holding is exempt', is_correct: false }] },
      { question_text: 'Why can\'t crypto users simply hide transactions from the IRS on a public blockchain?', explanation: 'Public blockchains are transparent — every transaction is permanently recorded and visible. The IRS uses blockchain analytics firms (Chainalysis, etc.) to trace transactions, and exchanges provide customer information when subpoenaed. The blockchain itself is a permanent audit trail.', options: [{ option_text: 'Blockchains are public records — analytics firms trace transactions and exchanges provide customer data', is_correct: true }, { option_text: 'The IRS has a backdoor into all crypto wallets', is_correct: false }, { option_text: 'All crypto transactions are automatically reported in real-time to the IRS', is_correct: false }, { option_text: 'Crypto transactions cannot be hidden because they require government approval', is_correct: false }] },
      { question_text: 'Transferring crypto between YOUR OWN wallets — is this a taxable event?', explanation: 'Transferring crypto between wallets you own (e.g., from Coinbase to your MetaMask, or between two of your hardware wallets) is NOT a taxable event. No sale or exchange occurred — you\'re just moving your own property between your own accounts.', options: [{ option_text: 'No — moving crypto between your own wallets is not a disposal or taxable event', is_correct: true }, { option_text: 'Yes — any movement of crypto triggers a capital gains calculation', is_correct: false }, { option_text: 'Only if the wallets are on different blockchains (cross-chain transfer)', is_correct: false }, { option_text: 'Yes, but you get a deduction for transfer fees that cancels it out', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 2. CAPITAL GAINS — SHORT vs. LONG TERM
  // ═══════════════════════════════════════════════════════
  {
    title: 'Short-Term vs. Long-Term Capital Gains',
    emoji: '📅',
    description: 'How long you hold crypto before selling determines which tax rate applies — and the difference between short-term (up to 37%) and long-term (0–20%) rates is enormous. This is the most impactful tax planning decision a crypto investor can make.',
    order_index: 2,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '📅 The One-Year Rule' } },
      { block_type: 'text', content: { text: 'The IRS uses a simple holding-period test to determine which capital gains rate applies:\n\n```\n  HOLDING PERIOD DETERMINES TAX RATE\n\n  Buy → Hold ≤ 365 days → Sell → SHORT-TERM gain/loss\n  Buy → Hold > 365 days → Sell → LONG-TERM gain/loss\n\n  One day can make an enormous difference.\n```\n\n**Short-Term Capital Gains (held 1 year or less):**\n- Taxed at your ORDINARY INCOME tax rate\n- Same rate as your wages from a job\n- 2024 rates: 10%, 12%, 22%, 24%, 32%, 35%, or 37%\n- A high-income earner in the 37% bracket pays 37% on short-term crypto gains\n\n**Long-Term Capital Gains (held more than 1 year):**\n- Taxed at PREFERENTIAL rates — significantly lower\n- 2024 rates: **0%, 15%, or 20%** depending on income\n- Most middle-income earners pay 15%\n- Even the highest earners pay only 20% + 3.8% net investment income tax\n\n**Key takeaway:** If you were going to sell crypto anyway, waiting until you cross the 1-year mark can cut your tax rate nearly in half.' } },

      { block_type: 'heading', content: { text: '💰 2024 Long-Term Capital Gains Tax Rates' } },
      { block_type: 'text', content: { text: '| Tax Rate | Single Filer Income | Married Filing Jointly |\n|---|---|---|\n| **0%** | Up to $47,025 | Up to $94,050 |\n| **15%** | $47,026 – $518,900 | $94,051 – $583,750 |\n| **20%** | Over $518,900 | Over $583,750 |\n\n*Source: IRS 2024 tax year brackets*\n\n**What this means in practice:**\n- A student with $40,000 in income who sells Bitcoin held 1+ year pays **0%** on the gains\n- An individual with $100,000 in income pays **15%** on long-term gains\n- A high earner with $600,000 income pays **20%** (plus 3.8% net investment income tax)\n\n**Contrast with short-term:**\n- Same student ($40,000 income) pays **12%** on short-term crypto gains\n- Same individual ($100,000 income) pays **22–24%** on short-term gains\n\nThe incentive to hold is built into the tax code.' } },

      { block_type: 'heading', content: { text: '📊 Capital Gains vs. Capital Losses' } },
      { block_type: 'text', content: { text: '**Capital losses offset capital gains:**\n\n```\n  EXAMPLE YEAR:\n\n  Bitcoin sale: +$10,000 gain\n  Solana sale:  -$4,000 loss\n  Ethereum sale: +$3,000 gain\n  ---\n  Net capital gain: $9,000 (taxable)\n```\n\n**If losses exceed gains:**\n- You can deduct up to **$3,000** of net capital losses against ordinary income per year\n- Remaining losses "carry forward" to future tax years — indefinitely\n\n**Short-term vs. long-term netting:**\n- Short-term gains and losses net against each other first\n- Long-term gains and losses net against each other first\n- If you end up with a net short-term gain AND a net long-term loss, they offset each other\n\n**Wash-sale rule (stocks):** With stocks, you cannot sell at a loss and buy back within 30 days to claim the loss. **As of current rules, the wash-sale rule does NOT apply to crypto** — allowing strategic tax-loss harvesting without a waiting period. (This may change with future legislation.)' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=xWZJ3Nc4pm8', title: 'Short-Term vs. Long-Term Crypto Gains: Save Big on Taxes', description: 'How holding period determines your crypto tax rate — the difference between short-term ordinary rates and long-term preferential rates, with real examples.' } },
      { block_type: 'article', content: { url: 'https://www.investopedia.com/terms/c/capital_gains_tax.asp', title: 'Capital Gains Tax — Investopedia', description: 'Investopedia\'s guide to capital gains tax — short-term vs long-term rates, 2024 tax brackets, and how losses offset gains.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'How long must you hold crypto to qualify for LONG-TERM capital gains tax rates?', explanation: 'You must hold crypto for MORE THAN one year (more than 365 days) to qualify for long-term capital gains rates. If you sell on exactly day 365, it\'s still short-term. Day 366 and beyond is long-term.', options: [{ option_text: 'More than one year (more than 365 days)', is_correct: true }, { option_text: 'Exactly 365 days — one full calendar year', is_correct: false }, { option_text: 'Two years or more — crypto has a longer qualifying period than stocks', is_correct: false }, { option_text: 'Six months — crypto has a shorter qualifying period than stocks', is_correct: false }] },
      { question_text: 'At what rate are SHORT-TERM crypto gains taxed?', explanation: 'Short-term capital gains (held 1 year or less) are taxed at your ordinary income rate — the same rate as your wages. This can be as high as 37% for high earners, making short-term trading very tax-inefficient.', options: [{ option_text: 'Your ordinary income tax rate — same as wages (10–37%)', is_correct: true }, { option_text: 'A flat 15% — the same as long-term capital gains for most earners', is_correct: false }, { option_text: 'Zero percent — short-term gains under $50,000 are exempt', is_correct: false }, { option_text: 'A flat 30% crypto tax as established by the 2024 crypto tax law', is_correct: false }] },
      { question_text: 'A student earns $35,000 per year and sells Bitcoin held for 18 months. What is their long-term capital gains rate?', explanation: 'With $35,000 in income (well below the $47,025 threshold for 2024), this student pays 0% long-term capital gains tax on their Bitcoin sale. The preferential 0% rate applies to lower and middle incomes.', options: [{ option_text: '0% — income falls below the $47,025 threshold for 2024', is_correct: true }, { option_text: '12% — the lowest ordinary income rate that applies to crypto', is_correct: false }, { option_text: '15% — the standard long-term capital gains rate', is_correct: false }, { option_text: '20% — long-term gains are always taxed at 20%', is_correct: false }] },
      { question_text: 'If you have $5,000 in crypto gains and $8,000 in crypto losses in the same year, how much can you deduct from ordinary income?', explanation: 'Net losses = $8,000 - $5,000 = $3,000. You can deduct up to $3,000 of net capital losses against ordinary income per year. The remaining $0 in this case carries forward (there are no excess losses here — exactly $3,000 net).', options: [{ option_text: '$3,000 — the maximum annual deduction for net capital losses against ordinary income', is_correct: true }, { option_text: '$8,000 — the full amount of your losses', is_correct: false }, { option_text: '$5,000 — the amount that offsets your gains', is_correct: false }, { option_text: '$0 — crypto losses cannot be deducted from ordinary income', is_correct: false }] },
      { question_text: 'Does the WASH-SALE rule apply to cryptocurrency (as of current US tax law)?', explanation: 'As of current rules, the wash-sale rule (which prevents claiming a loss if you rebuy within 30 days) does NOT apply to crypto — only to securities like stocks. This allows crypto investors to sell at a loss and immediately rebuy to harvest the loss for tax purposes. This may change with future legislation.', options: [{ option_text: 'No — the wash-sale rule currently does not apply to crypto, allowing immediate rebuying', is_correct: true }, { option_text: 'Yes — the same 30-day rule that applies to stocks also applies to crypto', is_correct: false }, { option_text: 'Yes — crypto has a stricter 60-day wash-sale period', is_correct: false }, { option_text: 'It varies by state — some states apply wash-sale rules to crypto', is_correct: false }] },
      { question_text: 'What happens to capital losses that EXCEED the $3,000 annual deduction limit?', explanation: 'Capital losses that exceed the $3,000 annual deduction limit carry forward indefinitely to future tax years. If you lose $15,000 this year and have no gains, you can deduct $3,000 per year for the next 5 years.', options: [{ option_text: 'They carry forward indefinitely to future tax years', is_correct: true }, { option_text: 'They expire at the end of the tax year — use them or lose them', is_correct: false }, { option_text: 'They can be donated to charity for a full deduction', is_correct: false }, { option_text: 'The IRS pays you a refund for losses exceeding $3,000', is_correct: false }] },
      { question_text: 'Why does the tax code INCENTIVIZE holding crypto for more than one year?', explanation: 'Long-term gains are taxed at 0%, 15%, or 20% — significantly below the 10–37% ordinary income rates for short-term gains. This preferential treatment is built into the tax code to reward long-term investing over short-term speculation.', options: [{ option_text: 'Long-term rates (0–20%) are far below short-term ordinary rates (10–37%) — a built-in reward for holding', is_correct: true }, { option_text: 'The IRS gives a deduction equal to inflation for long-term held assets', is_correct: false }, { option_text: 'Long-term held crypto can be reported in a foreign currency to reduce the amount', is_correct: false }, { option_text: 'The IRS only audits short-term traders — long-term holders are ignored', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 3. COST BASIS METHODS
  // ═══════════════════════════════════════════════════════
  {
    title: 'Cost Basis Methods — FIFO, LIFO & Specific ID',
    emoji: '🧮',
    description: 'When you\'ve bought the same crypto at different prices over time, which coins are you "selling" first? The answer changes your taxable gain significantly. Learn the three main methods and when each is most advantageous.',
    order_index: 3,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '🧮 What Is Cost Basis?' } },
      { block_type: 'text', content: { text: '**Cost basis** is the original price you paid for an asset, including fees. It determines your gain or loss when you sell.\n\n```\n  GAIN / LOSS CALCULATION\n\n  Sale Price - Cost Basis = Gain (positive) or Loss (negative)\n\n  Example:\n  Bought 1 BTC for $30,000 (cost basis)\n  Sold  1 BTC for $50,000\n  Gain = $50,000 - $30,000 = $20,000 taxable\n```\n\n**The complication:** Most crypto investors buy in multiple purchases over time — what do you do when you sell part of a holding?\n\n```\n  MULTIPLE PURCHASES:\n\n  Jan: Buy 1 BTC at $20,000  (cost basis: $20,000)\n  Apr: Buy 1 BTC at $35,000  (cost basis: $35,000)\n  Jul: Buy 1 BTC at $50,000  (cost basis: $50,000)\n\n  Dec: Sell 1 BTC at $60,000\n  QUESTION: Which BTC are you selling? The $20K one? The $35K one?\n  ANSWER: Depends on your cost basis method!\n```' } },

      { block_type: 'heading', content: { text: '📦 FIFO — First In, First Out' } },
      { block_type: 'text', content: { text: '**FIFO (First In, First Out)** assumes you sell the OLDEST coins first.\n\n```\n  FIFO EXAMPLE:\n\n  Purchases: Jan $20K, Apr $35K, Jul $50K\n  Selling 1 BTC at $60K in December\n\n  FIFO says: Sell the JANUARY $20K BTC first\n\n  Gain = $60,000 - $20,000 = $40,000\n\n  BUT: Held since January → more than 1 year\n  → LONG-TERM gain (lower tax rate)!\n```\n\n**When FIFO is advantageous:**\n- When your oldest coins have been held >1 year (long-term rates apply)\n- During a bull market when all purchases are below current price — the oldest (cheapest) purchase gives the largest gain, but long-term rates offset the tax\n\n**When FIFO is disadvantageous:**\n- In a bear market — selling the cheapest coins first means smaller losses to harvest\n- The IRS **defaults to FIFO** if you don\'t specify a method' } },

      { block_type: 'heading', content: { text: '📦 LIFO & Specific Identification' } },
      { block_type: 'text', content: { text: '**LIFO (Last In, First Out)** assumes you sell the NEWEST coins first.\n\n```\n  LIFO EXAMPLE:\n  (Same scenario: Dec sell 1 BTC at $60K)\n\n  LIFO says: Sell the JULY $50K BTC first\n\n  Gain = $60,000 - $50,000 = $10,000\n\n  BUT: Only held 5 months → SHORT-TERM gain\n  → Ordinary income rate (higher rate!)\n```\n\n**Note:** LIFO is not currently allowed for crypto by the IRS. It is included here for educational comparison.\n\n**Specific Identification (Spec ID)** — the most flexible method:\n- You identify EXACTLY which coins you are selling\n- Allows you to choose the highest-basis (most expensive) coins to minimize gain\n- OR choose coins held >1 year to get long-term rates\n- **Requires** keeping meticulous records of purchase dates, amounts, and prices\n- The IRS allows this — but you must make the selection BEFORE the sale, not after\n\n```\n  SPEC ID EXAMPLE:\n  (Same scenario: sell 1 BTC at $60K)\n\n  Choose to sell April $35K BTC:\n  Gain = $60,000 - $35,000 = $25,000\n  AND held since April (>1 year) → LONG-TERM\n```' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=oJLga0lNx-E', title: 'FIFO, LIFO, HIFO Explained! Crypto Taxes Made Simple', description: 'How to calculate crypto cost basis, the difference between FIFO and Specific Identification, and which method minimizes your tax bill in different market conditions.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/crypto-tax-loss-harvesting-what-is-it-and-how-does-it-work/', title: 'Cost Basis and Tax-Loss Harvesting in Crypto — CoinDesk', description: 'CoinDesk\'s guide to crypto cost basis methods and how to use them strategically to minimize taxes.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'What is COST BASIS in crypto taxation?', explanation: 'Cost basis is what you originally paid for a crypto asset, including any fees. When you sell, your taxable gain or loss equals the sale price minus your cost basis. Low cost basis = larger potential gain.', options: [{ option_text: 'The original price you paid for the asset — used to calculate your gain or loss', is_correct: true }, { option_text: 'The current market price of the asset', is_correct: false }, { option_text: 'The average price of all transactions on the day you sell', is_correct: false }, { option_text: 'The price the IRS assigns to your crypto for tax purposes', is_correct: false }] },
      { question_text: 'Under FIFO accounting, which coins are assumed to be sold first?', explanation: 'FIFO (First In, First Out) sells the OLDEST coins first — the first ones you bought. If those older coins have been held more than a year, the gains qualify for lower long-term rates.', options: [{ option_text: 'The oldest coins — the first ones purchased are the first ones sold', is_correct: true }, { option_text: 'The newest coins — the most recently purchased are sold first', is_correct: false }, { option_text: 'The coins with the highest purchase price', is_correct: false }, { option_text: 'Coins are sold in alphabetical order by blockchain', is_correct: false }] },
      { question_text: 'Which cost basis method gives you the MOST flexibility to minimize taxes?', explanation: 'Specific Identification lets you choose EXACTLY which coins you\'re selling — picking the highest-cost lots to minimize gains, or selecting coins held over a year to get long-term rates. It requires detailed record-keeping and selections before the sale.', options: [{ option_text: 'Specific Identification — you choose exactly which coins to sell for optimal tax treatment', is_correct: true }, { option_text: 'FIFO — the first purchased always results in the lowest tax', is_correct: false }, { option_text: 'LIFO — the most recently purchased always has the highest cost basis', is_correct: false }, { option_text: 'Average cost — divides total cost by total coins for simplicity', is_correct: false }] },
      { question_text: 'If you don\'t specify a cost basis method, what does the IRS default to?', explanation: 'The IRS defaults to FIFO (First In, First Out) if you do not specifically designate which coins you are selling. This means your oldest (likely cheapest) coins are sold first — which during a bull market creates larger gains.', options: [{ option_text: 'FIFO — the IRS default if no method is specified', is_correct: true }, { option_text: 'Average cost across all purchases', is_correct: false }, { option_text: 'LIFO — the most conservative method', is_correct: false }, { option_text: 'Specific ID — the most accurate method', is_correct: false }] },
      { question_text: 'You bought 2 BTC: one at $30,000 (6 months ago) and one at $50,000 (2 years ago). You sell 1 BTC today at $60,000. To MINIMIZE your tax bill, which coin should you sell using Specific ID?', explanation: 'The $50,000 BTC was bought 2 years ago → long-term gain = $60,000 - $50,000 = $10,000 at long-term rates. The $30,000 BTC is only 6 months old → short-term gain = $60,000 - $30,000 = $30,000 at ordinary rates. Selling the 2-year-old coin gives both a smaller gain AND a lower tax rate.', options: [{ option_text: 'The $50,000 BTC (2 years old) — smaller gain ($10K) AND long-term rate', is_correct: true }, { option_text: 'The $30,000 BTC (6 months old) — the cheapest cost basis maximizes the deduction', is_correct: false }, { option_text: 'It doesn\'t matter — both coins produce the same tax outcome', is_correct: false }, { option_text: 'The $30,000 BTC — older coins always produce lower taxes', is_correct: false }] },
      { question_text: 'Why does FIFO create LARGER gains during a bull market?', explanation: 'In a bull market, your oldest purchases were made at lower prices (before the price rose). FIFO sells these cheap old coins first, creating large spreads between cost basis and sale price — meaning larger taxable gains than if you sold more recently purchased coins with a higher cost basis.', options: [{ option_text: 'Oldest coins have the lowest cost basis — largest spread to today\'s higher price', is_correct: true }, { option_text: 'FIFO forces you to sell the most expensive coins in a bull market', is_correct: false }, { option_text: 'Bull markets double the applicable tax rate for FIFO users', is_correct: false }, { option_text: 'FIFO sells the most recently purchased coins — always the highest priced', is_correct: false }] },
      { question_text: 'What does it mean that you must make a Specific ID selection BEFORE a sale?', explanation: 'The IRS requires you to designate which specific lots (specific purchase transactions) you\'re selling BEFORE or at the time of the sale — not retroactively. This requires meticulous tracking. After-the-fact selection is not permitted and the IRS defaults to FIFO.', options: [{ option_text: 'You must identify which purchase lots you\'re selling before executing the trade', is_correct: true }, { option_text: 'You choose your method at the end of the year when filing taxes', is_correct: false }, { option_text: 'Your exchange automatically chooses the most tax-efficient lots', is_correct: false }, { option_text: 'Specific ID selections must be approved by the IRS before each sale', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 4. MINING, STAKING & INCOME
  // ═══════════════════════════════════════════════════════
  {
    title: 'Mining, Staking & Airdrop Taxes',
    emoji: '⛏️',
    description: 'Not all crypto arrives through purchases. Mining rewards, staking income, airdrops, and DeFi yield all have different tax treatments — and most are taxed as ordinary income when received.',
    order_index: 4,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '⛏️ Mining Rewards' } },
      { block_type: 'text', content: { text: '**Crypto mining rewards are taxable income when received.**\n\nWhen a miner successfully validates a block and receives Bitcoin or another coin as a reward:\n\n1. **At receipt:** The fair market value of the crypto on the day received is taxable as **ordinary income**\n   - If you mine 0.01 BTC when BTC = $50,000, you have $500 of income\n   - This is reported as self-employment income (Schedule C) if mining is a business\n   - Or as "other income" if it\'s a hobby (less favorable tax treatment for hobbyists)\n\n2. **When you sell:** The tax basis is the value at receipt. Any additional appreciation is a capital gain.\n   - If that 0.01 BTC later sells at $60,000 ($600), you have a $100 capital gain (not $600)\n\n**Self-employment tax:** Professional miners pay an additional 15.3% self-employment tax on top of income tax — because mining income is treated like running a business.' } },

      { block_type: 'heading', content: { text: '🏦 Staking Rewards' } },
      { block_type: 'text', content: { text: '**The IRS position on staking (as of current guidance):**\n\nStaking rewards are taxable as **ordinary income at the fair market value when received.**\n\nThis mirrors the treatment of mining rewards — when your Ethereum or Solana staking rewards hit your wallet, you owe income tax on the value at that moment.\n\n**Note — the Jarrett case:** Joshua Jarrett sued the IRS in 2022 arguing that newly created tokens from staking (like manufactured goods) should not be taxed until sold. The IRS initially agreed to refund his taxes rather than litigate, but also issued Notice 2023-14 reaffirming that staking rewards ARE income when received.\n\n**Practical implications:**\n- Staking across multiple DeFi protocols with frequent reward payments creates many small taxable events\n- The value fluctuates — $100 of ETH rewards received Tuesday may be worth $80 Thursday (you still owed tax on $100)\n- Tax software aggregates these automatically\n\n**Good news:** Your cost basis in staking rewards is the fair market value on receipt — so if the price drops after you receive them, you can harvest a capital loss when you sell.' } },

      { block_type: 'heading', content: { text: '🪂 Airdrops & Hard Forks' } },
      { block_type: 'text', content: { text: '**Airdrops** — tokens distributed to wallet holders for free:\n- IRS guidance: Airdrops are **ordinary income** at fair market value on the date received\n- This applies only when you have dominion and control (when you can access/sell them)\n- If an airdrop is worthless and illiquid, some tax professionals argue the value is $0 at receipt\n\n**Hard Forks** — when a blockchain splits and holders of the original receive new tokens:\n- The IRS (Revenue Ruling 2019-24) says hard fork tokens are also **ordinary income** at fair market value when received\n- Bitcoin Cash from the 2017 Bitcoin fork, for example, was taxable income for Bitcoin holders\n\n**DeFi Yield / Liquidity Mining Rewards:**\n- Interest and yield earned from DeFi protocols is treated as **ordinary income** when received\n- Some argue for "tax when sold" treatment for governance tokens, but IRS has not officially agreed\n\n**Key principle:** Any time you receive new crypto WITHOUT paying for it, the IRS generally treats it as income.' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=Y5i7wrBWW7A', title: 'Crypto Taxes Explained: Buying, Trading, Swapping, Staking, Rewards, Airdrops, Mining and More', description: 'The tax treatment of crypto mining rewards, staking income, and airdrops — all taxed as ordinary income when received, with the cost basis set at the value on the date received.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/how-is-staking-crypto-taxed/', title: 'How Is Staking Crypto Taxed? — CoinDesk', description: 'CoinDesk\'s explainer on staking tax treatment — the IRS position, the Jarrett case, and practical implications for DeFi yield farmers.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'When are cryptocurrency MINING REWARDS taxed?', explanation: 'Mining rewards are taxed as ordinary income when received — at the fair market value on the date you received them. This first tax is on the income. When you later sell those coins, any additional gain is a capital gain.', options: [{ option_text: 'As ordinary income when received — at the fair market value on receipt date', is_correct: true }, { option_text: 'Only when you sell the mined coins — not when you receive them', is_correct: false }, { option_text: 'At a flat 0% rate — mining creates new currency, not taxable income', is_correct: false }, { option_text: 'At the end of the year, based on the annual average price', is_correct: false }] },
      { question_text: 'You mine 0.1 BTC when Bitcoin is worth $40,000. You later sell it when Bitcoin is worth $50,000. What is your CAPITAL GAIN?', explanation: 'You received 0.1 BTC worth $4,000 as income (cost basis = $4,000). You sold it for $5,000. Capital gain = $5,000 - $4,000 = $1,000. You already paid income tax on the $4,000 when you received it.', options: [{ option_text: '$1,000 — the gain above your $4,000 cost basis (value at receipt)', is_correct: true }, { option_text: '$5,000 — the full sale price', is_correct: false }, { option_text: '$4,000 — the original value when mined', is_correct: false }, { option_text: '$0 — mining rewards are tax-free regardless of later sale price', is_correct: false }] },
      { question_text: 'How does the IRS treat STAKING REWARDS (per current guidance)?', explanation: 'Per IRS Notice 2023-14, staking rewards are ordinary income at the fair market value when received — the same treatment as mining rewards. The cost basis in the received tokens equals that value.', options: [{ option_text: 'Ordinary income at fair market value when received — per IRS Notice 2023-14', is_correct: true }, { option_text: 'Tax-deferred until sold — staking creates property, not income', is_correct: false }, { option_text: 'Capital gains income when the rewards are eventually sold', is_correct: false }, { option_text: 'Tax-free if the staking rewards are locked for at least 6 months', is_correct: false }] },
      { question_text: 'You receive a $500 airdrop of a new token on March 1. By April 1 the token is worth $0. How much income do you report?', explanation: 'You report $500 of ordinary income — the fair market value on March 1 when you received it. The subsequent crash creates a capital loss when you sell, but the income on receipt was $500. (Some tax professionals argue value is $0 if the token is illiquid, but the IRS default is value at receipt.)', options: [{ option_text: '$500 — the fair market value on the date you received the airdrop', is_correct: true }, { option_text: '$0 — the token lost all value so you had no real income', is_correct: false }, { option_text: '$250 — average the value over the month you held it', is_correct: false }, { option_text: 'It is not reportable — airdrops are gifts, not income', is_correct: false }] },
      { question_text: 'What additional tax do PROFESSIONAL MINERS pay that regular investors do not?', explanation: 'Professional miners pay self-employment tax (15.3%) on their mining income in addition to regular income tax, because mining income is treated as business income (Schedule C). Hobby miners pay income tax but not self-employment tax — though they lose some deductions.', options: [{ option_text: 'Self-employment tax (15.3%) — mining income is treated as business income', is_correct: true }, { option_text: 'A 50% surcharge — mining income is taxed twice', is_correct: false }, { option_text: 'An energy surcharge — electricity used for mining is taxed by the IRS', is_correct: false }, { option_text: 'No additional tax — miners and investors are taxed identically', is_correct: false }] },
      { question_text: 'You receive Bitcoin Cash tokens from the 2017 Bitcoin hard fork. According to IRS Revenue Ruling 2019-24, how is this treated?', explanation: 'IRS Revenue Ruling 2019-24 established that hard fork tokens are ordinary income at their fair market value when received. Bitcoin Cash received by Bitcoin holders in 2017 was therefore taxable income to those holders.', options: [{ option_text: 'Ordinary income at the fair market value when received', is_correct: true }, { option_text: 'Tax-free — hard forks simply split existing property with no new value created', is_correct: false }, { option_text: 'A capital gain based on Bitcoin\'s original purchase price', is_correct: false }, { option_text: 'Reportable only if you sell the Bitcoin Cash within the same tax year', is_correct: false }] },
      { question_text: 'What is the COST BASIS of staking rewards or mining rewards for future capital gains calculations?', explanation: 'The cost basis of staking/mining rewards is the fair market value on the date you received them (the same amount you reported as income). If you reported $200 of staking income when you received tokens, your cost basis in those tokens is $200.', options: [{ option_text: 'The fair market value on the date received — the same amount reported as income', is_correct: true }, { option_text: '$0 — since you didn\'t pay for them, the basis is zero', is_correct: false }, { option_text: 'The original cost of your mining equipment', is_correct: false }, { option_text: 'The price at the end of the tax year you received them', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 5. TAX-LOSS HARVESTING
  // ═══════════════════════════════════════════════════════
  {
    title: 'Tax-Loss Harvesting',
    emoji: '🌾',
    description: 'Tax-loss harvesting is the practice of strategically selling crypto at a loss to reduce your tax bill — without necessarily staying out of the market. It\'s one of the most effective legal tax strategies for crypto investors.',
    order_index: 5,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '🌾 What Is Tax-Loss Harvesting?' } },
      { block_type: 'text', content: { text: '**Tax-loss harvesting** is selling a crypto asset at a loss to realize the loss for tax purposes — even if you believe the asset will recover — then immediately rebuying if you want to maintain your position.\n\n**Why it works:**\n- Capital losses offset capital gains dollar-for-dollar\n- Up to $3,000 of excess losses can offset ordinary income per year\n- Additional excess losses carry forward indefinitely\n\n**The crypto advantage:** Unlike stocks, crypto has NO wash-sale rule (currently). You can:\n1. Sell ETH at a $5,000 loss\n2. Immediately rebuy ETH at the same price\n3. Claim the $5,000 loss on your taxes\n4. Still have the same ETH position (your cost basis is now reset to the lower price)\n\n```\n  TAX-LOSS HARVEST EXAMPLE:\n\n  Bought 2 ETH at $3,000 each = $6,000 cost basis\n  Current price: $2,500 → current value: $5,000\n  Unrealized loss: $1,000\n\n  Step 1: Sell 2 ETH at $2,500 → realize $1,000 loss\n  Step 2: Immediately rebuy 2 ETH at $2,500\n  Step 3: New cost basis: $5,000 (2 × $2,500)\n  Step 4: Claim $1,000 loss to offset gains or income\n  Result: Same position, $1,000 tax benefit\n```' } },

      { block_type: 'heading', content: { text: '📊 When Tax-Loss Harvesting Matters Most' } },
      { block_type: 'text', content: { text: '**Tax-loss harvesting is most valuable when:**\n\n1. **You have capital gains to offset** — if you sold winning crypto, harvesting losses reduces the net taxable gain\n2. **You\'re in a high tax bracket** — a 37% earner saves $370 in taxes per $1,000 of harvested losses; a 12% earner saves $120\n3. **Crypto is down significantly** — bear markets create large unrealized losses that can be harvested\n4. **Year-end** — December is the most common time to harvest, reviewing your portfolio for unrealized losses before December 31\n\n**The "reset" effect:**\n- After harvesting, your cost basis is LOWER (you reset it to the current market price)\n- If the asset then recovers and you sell, you\'ll have a LARGER future taxable gain\n- Tax-loss harvesting is a timing strategy — it doesn\'t eliminate taxes, it defers them to the future\n\n**Important:** The goal is usually to lock in a LOSS now (when your tax rate may be high) and pay a gain later (when you may have lower income, or the gain may qualify for long-term rates).' } },

      { block_type: 'heading', content: { text: '⚠️ Watch for Future Wash-Sale Rule Changes' } },
      { block_type: 'text', content: { text: 'Congress has proposed applying the wash-sale rule to crypto in multiple bills, including the 2021 Build Back Better Act and subsequent proposals.\n\n**Current status:** As of current law, the wash-sale rule does NOT apply to cryptocurrency.\n\n**What to watch:** If the wash-sale rule is extended to crypto, the strategy of sell-and-immediately-rebuy would no longer produce a tax loss. The 30-day waiting period would apply.\n\n**Planning consideration:**\n- The most responsible approach is to consult a tax professional before executing large harvesting strategies\n- Documentation is critical — you must record the exact date, price, amount, and transaction hash for every sell and rebuy\n- Crypto tax software (Koinly, CoinTracker, TaxBit) automates this tracking and flags harvesting opportunities' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=rFUjXUVpFEQ', title: 'Cryptocurrency Tax Loss Harvesting 101 — Save Money On Your Taxes', description: 'How tax-loss harvesting works in crypto, why there\'s no wash-sale rule currently, and the step-by-step process of harvesting losses while maintaining your market position.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/crypto-tax-loss-harvesting-what-is-it-and-how-does-it-work/', title: 'Crypto Tax-Loss Harvesting — CoinDesk', description: 'CoinDesk\'s guide to tax-loss harvesting strategies — what it is, why crypto has advantages over stocks, and when it makes sense to do it.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'What is TAX-LOSS HARVESTING?', explanation: 'Tax-loss harvesting is strategically selling an asset at a loss to realize the loss for tax purposes — reducing your taxable capital gains or ordinary income. In crypto, you can often immediately rebuy since the wash-sale rule doesn\'t currently apply.', options: [{ option_text: 'Selling crypto at a loss to realize the loss for tax purposes, then potentially rebuying', is_correct: true }, { option_text: 'Waiting until a loss has grown to maximum before selling', is_correct: false }, { option_text: 'Donating losing crypto to charity to get a deduction', is_correct: false }, { option_text: 'Moving losing crypto to a hardware wallet to defer the tax', is_correct: false }] },
      { question_text: 'Why does crypto tax-loss harvesting have an ADVANTAGE over stock tax-loss harvesting?', explanation: 'Stocks are subject to the wash-sale rule — you can\'t claim a loss if you rebuy within 30 days. Crypto currently has no wash-sale rule, so you can sell at a loss and immediately rebuy the same crypto, harvesting the tax loss while maintaining your position.', options: [{ option_text: 'No wash-sale rule — you can sell and immediately rebuy the same crypto to claim the loss', is_correct: true }, { option_text: 'Crypto losses are tax-deductible at 200% — double the benefit of stocks', is_correct: false }, { option_text: 'Crypto losses carry forward for longer than stock losses', is_correct: false }, { option_text: 'Crypto losses offset ordinary income at a higher rate than stock losses', is_correct: false }] },
      { question_text: 'You harvest a $5,000 loss in December. What happens to your COST BASIS in the position you rebuy?', explanation: 'When you sell and rebuy at a lower price, your cost basis RESETS to the new (lower) purchase price. This means if the asset recovers and you sell later, you\'ll have a larger taxable gain than if you had never harvested. Tax-loss harvesting defers taxes, it doesn\'t eliminate them.', options: [{ option_text: 'It resets to the current (lower) purchase price — future gains will be larger', is_correct: true }, { option_text: 'It stays the same as your original purchase price', is_correct: false }, { option_text: 'It goes to zero — the rebuy creates a fresh position with no basis', is_correct: false }, { option_text: 'The IRS adjusts your basis to account for the harvested loss', is_correct: false }] },
      { question_text: 'Tax-loss harvesting is most valuable when you are in what situation?', explanation: 'Tax-loss harvesting provides the most benefit when you have capital GAINS to offset (every dollar of loss reduces your taxable gains) AND when you\'re in a HIGH TAX BRACKET (where each dollar of loss saves more in taxes).', options: [{ option_text: 'You have capital gains to offset AND you\'re in a high tax bracket', is_correct: true }, { option_text: 'You have only unrealized gains and want to protect them', is_correct: false }, { option_text: 'You\'re in a low tax bracket — harvesting saves more at low rates', is_correct: false }, { option_text: 'You have no other income — losses against $0 income maximize the benefit', is_correct: false }] },
      { question_text: 'What is the primary RISK of tax-loss harvesting?', explanation: 'The main risk is that after you sell to harvest the loss, the price could sharply increase before you can rebuy. You\'d have locked in your loss on paper and also missed the rally. Tax-loss harvesting involves market timing risk.', options: [{ option_text: 'The price could rise sharply after you sell, and you miss the rally before rebuying', is_correct: true }, { option_text: 'The IRS will audit you for doing multiple sell-and-rebuy transactions', is_correct: false }, { option_text: 'Losses can only be harvested once per crypto asset, per year', is_correct: false }, { option_text: 'Rebuying immediately creates a "constructive sale" that voids the loss', is_correct: false }] },
      { question_text: 'What should you WATCH FOR that could eliminate the crypto tax-loss harvesting advantage?', explanation: 'Congress has proposed extending the wash-sale rule to crypto in multiple bills. If passed, the 30-day waiting period would apply and you could no longer sell and immediately rebuy to harvest losses while maintaining your position.', options: [{ option_text: 'Legislation extending the wash-sale rule to cryptocurrency', is_correct: true }, { option_text: 'The IRS reducing the capital loss deduction limit below $3,000', is_correct: false }, { option_text: 'Tax rates being lowered — making harvesting less valuable', is_correct: false }, { option_text: 'Exchanges being required to automatically harvest losses for customers', is_correct: false }] },
      { question_text: 'Tax-loss harvesting ELIMINATES taxes on your crypto gains — true or false?', explanation: 'FALSE. Tax-loss harvesting DEFERS taxes — it moves them to the future. When you rebuy at a lower price, your cost basis resets lower. When you eventually sell, the lower basis creates a larger future gain. You\'re trading a tax bill now for a (potentially) larger one later.', options: [{ option_text: 'False — it defers taxes to the future, not eliminates them', is_correct: true }, { option_text: 'True — losses permanently offset all future gains from that asset', is_correct: false }, { option_text: 'True — but only if the asset is held for 5+ years after rebuying', is_correct: false }, { option_text: 'True for short-term gains, false for long-term gains', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 6. REPORTING & FORMS
  // ═══════════════════════════════════════════════════════
  {
    title: 'Reporting Crypto on Your Tax Return',
    emoji: '📝',
    description: 'The forms you need, where crypto goes on your tax return, how exchanges report your transactions, and what happens when you don\'t report.',
    order_index: 6,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '📝 The Forms You Need' } },
      { block_type: 'text', content: { text: '**Form 8949 — Sales and Other Dispositions of Capital Assets**\n- This is where you list every taxable crypto transaction\n- Each sale/trade/spend gets its own line: description, date acquired, date sold, proceeds, cost basis, gain or loss\n- Short-term transactions (held ≤1 year): Part I\n- Long-term transactions (held >1 year): Part II\n\n**Schedule D — Capital Gains and Losses**\n- Totals from Form 8949 flow here\n- Short-term net gain/loss and long-term net gain/loss are combined\n- Final number flows to your Form 1040\n\n**Schedule C — Profit or Loss from Business**\n- Mining income reported here if you\'re a professional miner\n- Subject to self-employment tax (15.3%)\n\n**Schedule 1 (Form 1040) — Additional Income**\n- Staking rewards and airdrops reported as "Other Income"\n- Hobby mining income here (no self-employment tax, but also limited deductions)\n\n**Form 1099-DA** (starting tax year 2025)\n- Your exchange sends this to you AND the IRS\n- Shows your crypto transactions — your report must match' } },

      { block_type: 'heading', content: { text: '🏦 How Exchanges Report to the IRS' } },
      { block_type: 'text', content: { text: '**Current system (before 2025):**\n- Exchanges like Coinbase issue Form 1099-MISC for rewards/staking income over $600\n- Some exchanges issue Form 1099-B for trading activity\n- The IRS cross-references these against your return\n\n**New system (starting 2025):**\n- Form 1099-DA is REQUIRED from all digital asset brokers\n- Includes every buy, sell, trade, and transfer date and amount\n- This is the IRS\'s biggest crypto enforcement upgrade ever\n- If your return doesn\'t match the 1099-DA, expect questions\n\n**DeFi and DEX trades:**\n- Currently, decentralized exchanges do NOT have reporting requirements\n- New rules may extend 1099-DA to DEX operators — still evolving\n- You are still legally required to self-report DeFi transactions even without a 1099\n\n**The matching problem:** If exchanges report your transactions to the IRS and you don\'t include them on your return, the IRS computer matches and sends you a CP2000 notice (a proposed bill for the unreported income).' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=zY0k3Vq_JoE', title: 'How To Report Crypto On Form 8949', description: 'Which tax forms to use for crypto gains and losses, how Form 8949 and Schedule D work, and how exchange 1099-DA reporting changes your obligations starting in 2025.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/crypto-taxes-usa-guide/', title: 'Complete US Crypto Tax Guide — CoinDesk', description: 'CoinDesk\'s complete breakdown of US crypto tax reporting — which forms to use, what exchanges report, and what to do if you missed prior year transactions.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'On which form do you list EACH individual crypto sale or trade?', explanation: 'Form 8949 (Sales and Other Dispositions of Capital Assets) is where every crypto disposal gets its own line — date acquired, date sold, proceeds, cost basis, and gain or loss. These totals flow to Schedule D.', options: [{ option_text: 'Form 8949 — one line per transaction, totals flow to Schedule D', is_correct: true }, { option_text: 'Schedule D — you list individual transactions directly here', is_correct: false }, { option_text: 'Form 1099-DA — you file this directly with the IRS', is_correct: false }, { option_text: 'Form 1040 — individual crypto trades go on the main return', is_correct: false }] },
      { question_text: 'On Form 8949, where do long-term capital gains (held >1 year) go?', explanation: 'Form 8949 has two parts: Part I for short-term (held 1 year or less) and Part II for long-term (held more than 1 year). Separating them ensures the correct tax rate applies to each category.', options: [{ option_text: 'Part II — separate from short-term transactions to ensure correct rates', is_correct: true }, { option_text: 'Part I — all crypto gains go in the same section', is_correct: false }, { option_text: 'A separate supplemental schedule attached to Form 8949', is_correct: false }, { option_text: 'Directly on Schedule D, bypassing Form 8949', is_correct: false }] },
      { question_text: 'Starting with tax year 2025, what new form must exchanges send to customers and the IRS?', explanation: 'Form 1099-DA (Digital Assets) is a new IRS form required from crypto exchanges starting with tax year 2025. It reports customer transactions directly to both the customer and the IRS — similar to how stock brokers use Form 1099-B.', options: [{ option_text: 'Form 1099-DA — Digital Assets form, like a stock broker\'s 1099-B', is_correct: true }, { option_text: 'Form 1099-CRYPTO — a pre-existing form expanded to all exchanges', is_correct: false }, { option_text: 'Form W-2 Crypto — only for miners who earn over $600', is_correct: false }, { option_text: 'Form 8949-DA — an extension of the existing capital gains form', is_correct: false }] },
      { question_text: 'Are DeFi and DEX transactions required to be self-reported even without a 1099?', explanation: 'YES. Even if a decentralized exchange doesn\'t send you a 1099, you are legally required to report all taxable crypto transactions including DeFi trades. "I didn\'t get a form" is not a valid defense for unreported taxable income.', options: [{ option_text: 'Yes — legal obligation exists regardless of whether you receive a 1099', is_correct: true }, { option_text: 'No — if no 1099 is issued, the transaction is not reportable', is_correct: false }, { option_text: 'Only if the DEX trade exceeded $10,000 in value', is_correct: false }, { option_text: 'DeFi is currently completely tax-exempt under US law', is_correct: false }] },
      { question_text: 'Professional crypto mining income is reported on which schedule?', explanation: 'Professional miners (those running mining as a business) report income and expenses on Schedule C (Profit or Loss from Business). This makes them subject to self-employment tax (15.3%) but also allows deduction of business expenses like electricity and equipment.', options: [{ option_text: 'Schedule C — treated as business income, subject to self-employment tax', is_correct: true }, { option_text: 'Schedule D — mining income is a capital gain', is_correct: false }, { option_text: 'Form 8949 — one line per block mined', is_correct: false }, { option_text: 'Schedule E — passive income from mining operations', is_correct: false }] },
      { question_text: 'What happens if your tax return doesn\'t match the 1099-DA your exchange sends to the IRS?', explanation: 'The IRS computer matching system sends a CP2000 notice — a proposed additional tax bill for the unreported income. The IRS calculated what you owe based on the 1099 and will collect it. This can also trigger penalties and interest.', options: [{ option_text: 'The IRS sends a CP2000 notice proposing additional tax — plus potential penalties and interest', is_correct: true }, { option_text: 'Nothing — the IRS only audits returns with over $1 million in transactions', is_correct: false }, { option_text: 'Your return is automatically corrected by the IRS with no penalty', is_correct: false }, { option_text: 'The exchange is penalized for incorrect reporting', is_correct: false }] },
      { question_text: 'Where does STAKING INCOME appear on your tax return?', explanation: 'Staking rewards (and airdrop income) are reported as "Other Income" on Schedule 1 of Form 1040. If staking is run as a business, it may go on Schedule C instead. Either way, it\'s ordinary income — not capital gains.', options: [{ option_text: 'Schedule 1 as "Other Income" — ordinary income, not capital gains', is_correct: true }, { option_text: 'Schedule D — staking rewards are long-term capital gains', is_correct: false }, { option_text: 'Form 8949 — each staking reward is listed separately as a sale', is_correct: false }, { option_text: 'Staking income is reported on your W-2 if your staking income exceeds $600', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 7. CRYPTO TAX SOFTWARE
  // ═══════════════════════════════════════════════════════
  {
    title: 'Crypto Tax Software',
    emoji: '💻',
    description: 'Tracking thousands of DeFi transactions manually is impractical. Crypto tax software automates the calculation — connecting to exchanges and wallets, calculating gains and losses, and generating ready-to-file tax reports.',
    order_index: 7,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '💻 Why You Need Specialized Software' } },
      { block_type: 'text', content: { text: 'Standard tax software (TurboTax, H&R Block) can handle a few crypto transactions manually entered — but active crypto users may have thousands:\n\n- Every DeFi swap on Uniswap = a taxable event\n- Every NFT mint or sale = a taxable event\n- Every staking reward received = income\n- Every liquidity pool deposit/withdrawal may have tax implications\n- Gas fees affect cost basis calculations\n\nDoing this manually for 500+ transactions is practically impossible and error-prone. Crypto tax software connects directly to exchanges and wallets and does the work automatically.\n\n**The major players:**\n\n| Software | Best For | Price Range |\n|---|---|---|\n| **Koinly** | International users, DeFi | Free–$279/yr |\n| **CoinTracker** | TurboTax integration | Free–$599/yr |\n| **TaxBit** | US-focused, exchanges | Free–$50/yr |\n| **TokenTax** | Complex DeFi, NFTs | $65–$3,500/yr |\n| **ZenLedger** | CPAs and accountants | $49–$999/yr |\n| **CoinLedger** | Beginners, simple trades | Free–$99/yr |\n\nPricing usually based on number of transactions.' } },

      { block_type: 'heading', content: { text: '🔌 How It Works' } },
      { block_type: 'text', content: { text: '**Step 1: Connect your accounts**\n- API connection to exchanges (Coinbase, Binance, Kraken) — read-only API keys\n- Import wallet addresses (Ethereum, Bitcoin, Solana addresses)\n- Software pulls all historical transactions automatically\n\n**Step 2: Review and classify**\n- Software categorizes transactions: trade, income, gift, transfer, etc.\n- You review flagged items — some transactions need manual classification\n- DeFi interactions can be complex — software may need help with obscure protocols\n\n**Step 3: Reconcile**\n- Check that all wallets and exchanges are connected\n- Missing data creates errors — a transfer from an unconnected wallet looks like a phantom purchase\n- All transactions from ALL sources must be included\n\n**Step 4: Generate reports**\n- Form 8949 ready for your tax preparer or direct upload to TurboTax\n- Capital gains summary (short-term vs. long-term)\n- Income report (staking, mining, airdrops)\n- Tax-loss harvesting opportunities flagged\n\n**The cost is worth it:** $79 for software that correctly handles 1,000 transactions is far cheaper than a CPA doing it manually or paying penalties for errors.' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=8MWzolA8FC8', title: 'Best Crypto Tax Software 2025 — CoinLedger vs. Koinly Tax Tools Comparison', description: 'A comparison of the leading crypto tax software tools — how they work, what they connect to, and which is best for different types of crypto users.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/best-crypto-tax-software/', title: 'Best Crypto Tax Software — CoinDesk', description: 'CoinDesk\'s reviewed comparison of crypto tax software — Koinly, CoinTracker, TaxBit, and others — with pricing and feature breakdowns.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'Why is standard tax software (TurboTax) often insufficient for active crypto users?', explanation: 'Active crypto users may have hundreds or thousands of taxable events — every DeFi swap, NFT transaction, staking reward, and liquidity pool interaction. Standard tax software requires manual entry and can\'t connect to blockchain data automatically.', options: [{ option_text: 'Hundreds of DeFi/NFT transactions cannot be manually entered accurately — specialized software automates this', is_correct: true }, { option_text: 'TurboTax is banned from handling crypto transactions by the IRS', is_correct: false }, { option_text: 'Standard software calculates crypto taxes incorrectly even for simple transactions', is_correct: false }, { option_text: 'TurboTax only handles USD transactions — not digital assets', is_correct: false }] },
      { question_text: 'When connecting a crypto exchange to tax software via API, what type of key should you use?', explanation: 'Always use READ-ONLY API keys when connecting exchanges to tax software. Read-only keys can pull transaction history but cannot execute trades or withdraw funds. This protects your assets if the tax software is ever compromised.', options: [{ option_text: 'Read-only API keys — they can pull data but cannot trade or withdraw', is_correct: true }, { option_text: 'Full access API keys — tax software needs trading access to calculate accurately', is_correct: false }, { option_text: 'Your exchange login and password directly', is_correct: false }, { option_text: 'API keys are not needed — tax software uses blockchain scanning only', is_correct: false }] },
      { question_text: 'What happens if you forget to connect ONE of your wallets to crypto tax software?', explanation: 'Missing wallet data creates errors — a transfer from an unconnected wallet appears as a phantom "purchase" with no cost basis, inflating your gains. All wallets from all years must be included for accurate calculations.', options: [{ option_text: 'Transfers from the missing wallet appear as phantom purchases with no cost basis — inflating gains', is_correct: true }, { option_text: 'The software automatically finds missing wallets using blockchain scanning', is_correct: false }, { option_text: 'Only the transactions TO connected wallets need to be reported', is_correct: false }, { option_text: 'Missing wallets are fine — each wallet is taxed independently', is_correct: false }] },
      { question_text: 'What is the main OUTPUT of crypto tax software that you give to a tax preparer?', explanation: 'Crypto tax software generates a completed Form 8949 (or a file that can be directly imported into tax software) listing every transaction with cost basis and gain/loss calculated. This is what flows to Schedule D and ultimately your Form 1040.', options: [{ option_text: 'A completed Form 8949 listing all transactions with gains and losses calculated', is_correct: true }, { option_text: 'A summary PDF for your records — not an official IRS form', is_correct: false }, { option_text: 'Your complete tax return, ready to file — no CPA needed', is_correct: false }, { option_text: 'A list of wallets for the IRS to audit directly', is_correct: false }] },
      { question_text: 'Which type of crypto user would most benefit from the most expensive crypto tax software plans?', explanation: 'The most expensive plans handle the highest transaction volumes and most complex activity — NFT trading, DeFi protocols, liquidity pools, bridging between chains. Casual holders with a few exchange trades need only the free or cheapest tier.', options: [{ option_text: 'Heavy DeFi/NFT users with thousands of transactions across many protocols', is_correct: true }, { option_text: 'Long-term Bitcoin holders with 2-3 annual transactions', is_correct: false }, { option_text: 'First-time crypto buyers who only hold and have never sold', is_correct: false }, { option_text: 'Anyone using a US-based exchange — they require the premium plan for compliance', is_correct: false }] },
      { question_text: 'Gas fees paid for Ethereum transactions — how do they affect your taxes?', explanation: 'Gas fees increase your cost basis for purchases (or reduce proceeds for sales). For example, if you buy ETH worth $1,000 and pay $50 in gas, your cost basis is $1,050. This means gas fees reduce your taxable gain when you eventually sell.', options: [{ option_text: 'They increase cost basis for buys (reducing future gain) or reduce proceeds for sells', is_correct: true }, { option_text: 'Gas fees are not tax-relevant and should be ignored', is_correct: false }, { option_text: 'Gas fees create a separate deductible business expense for all users', is_correct: false }, { option_text: 'Gas fees are taxed separately at a flat 25% rate by the IRS', is_correct: false }] },
      { question_text: 'What is the best practice for keeping crypto records year-round to minimize tax season stress?', explanation: 'Connecting all wallets and exchanges to tax software from the start (or keeping detailed records of every transaction as it happens) prevents the nightmare of reconstructing years of activity at tax time. Many users only connect software in March and discover missing or broken transaction data.', options: [{ option_text: 'Keep all wallets and exchanges connected to tax software year-round, reviewing periodically', is_correct: true }, { option_text: 'Wait until tax season — exchanges send everything you need on 1099-DA', is_correct: false }, { option_text: 'Screenshot every transaction — photos are acceptable IRS documentation', is_correct: false }, { option_text: 'Only track transactions over $1,000 — small trades are de minimis', is_correct: false }] },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // 8. INTERNATIONAL & ADVANCED
  // ═══════════════════════════════════════════════════════
  {
    title: 'International Tax & Advanced Strategies',
    emoji: '🌍',
    description: 'How different countries tax crypto, FBAR requirements for foreign exchange accounts, crypto gifts and donations, and the most important rule in tax strategy: consult a professional.',
    order_index: 8,
    tokens_reward: 35,
    pass_threshold: 70,
    blocks: [
      { block_type: 'text', content: { text: '\u26a0\ufe0f **This lesson is for educational purposes only \u2014 it is not financial or tax advice.** Tax laws vary by individual situation and jurisdiction and change frequently. Always consult a qualified tax professional or CPA before making real tax decisions.' } },
      { block_type: 'heading', content: { text: '🌍 How Other Countries Tax Crypto' } },
      { block_type: 'text', content: { text: '| Country | Tax Treatment | Rate |\n|---|---|---|\n| **USA** | Property — capital gains tax | 0–37% |\n| **UK** | Capital gains tax | 10–20% (18–24% from April 2024) |\n| **Germany** | Tax-FREE if held 1+ year | 0% if >1yr; up to 45% if <1yr |\n| **Portugal** | Was tax-free; taxed since 2023 | 28% on gains |\n| **El Salvador** | Tax-free — Bitcoin is legal tender | 0% |\n| **Singapore** | No capital gains tax | 0% (income tax if trading as profession) |\n| **Australia** | Capital gains; 50% discount if held >1yr | Ordinary rate ÷ 2 if >1yr |\n| **UAE** | No personal income tax | 0% |\n| **India** | Flat tax on crypto gains | 30% + surcharges |\n| **Brazil** | Capital gains above exemption threshold | 15–22.5% |\n\n**Key observation:** Germany\'s "1-year rule" is one of the most favorable in the world — hold Bitcoin or Ethereum for over a year and sell tax-free. Many European crypto investors have utilized this rule.' } },

      { block_type: 'heading', content: { text: '📋 FBAR — Foreign Account Reporting' } },
      { block_type: 'text', content: { text: '**FBAR (FinCEN Form 114)** — Report of Foreign Bank and Financial Accounts:\n\nUS citizens and residents must file an FBAR if they have financial accounts in foreign countries with a combined value exceeding **$10,000** at any point during the year.\n\n**Does crypto on foreign exchanges count?**\n- Current IRS position: Crypto held on foreign exchanges may not currently trigger FBAR requirements\n- The Treasury has proposed extending FBAR to include foreign crypto exchanges\n- This is an evolving area — consult a tax professional if you use non-US exchanges\n\n**FATCA:** Foreign Account Tax Compliance Act may also apply if you have significant assets abroad. Failure to report foreign accounts can result in penalties up to $10,000 per violation (or 50% of account value for willful violations).' } },

      { block_type: 'heading', content: { text: '🎁 Gifts, Donations & Inheritance' } },
      { block_type: 'text', content: { text: '**Gifting Crypto:**\n- Giving crypto as a gift is NOT a taxable event for the GIVER (up to $18,000 per person in 2024 — the annual gift exclusion)\n- The RECIPIENT inherits your cost basis and holding period\n- When they sell, they pay taxes based on your original purchase price\n\n**Donating Crypto to Charity:**\n- Donating appreciated crypto directly to a qualified charity may be one of the best tax strategies:\n  - You get a deduction for the FULL fair market value at time of donation\n  - You pay NO capital gains tax on the appreciation\n  - The charity, being tax-exempt, pays no tax either\n- Better than selling and donating cash: no capital gains tax on the appreciated amount\n\n**Inheriting Crypto:**\n- Inherited crypto receives a **stepped-up basis** — the cost basis is reset to the fair market value on the date of the original owner\'s death\n- This eliminates all capital gains that accrued during the deceased\'s lifetime\n- Estate tax may apply for very large estates (federal threshold: $13.61 million in 2024)' } },

      { block_type: 'heading', content: { text: '📺 Watch & Learn' } },
      { block_type: 'video', content: { url: 'https://www.youtube.com/watch?v=f6dBMR0zsNs', title: 'Top Places With No Crypto Tax You Need to Know', description: 'How different countries tax cryptocurrency — US vs UK vs Germany vs Singapore vs UAE, FBAR requirements, and crypto gifting and donation strategies.' } },
      { block_type: 'article', content: { url: 'https://www.coindesk.com/learn/crypto-taxes-usa-guide/', title: 'Crypto Gift Tax & Charity Donations — CoinDesk', description: 'How crypto gifts, inheritances, and charitable donations are taxed — including the stepped-up basis rule for inherited crypto and charity donation strategies.' } },
      { block_type: 'text', content: { text: '\u26a0\ufe0f **Not financial advice.** CryptoClassroom is an educational simulator for entertainment and learning purposes only. No real money is used. Past simulated performance does not reflect real-world results. Always consult a qualified financial advisor before making real investment decisions.' } },
    ],
    questions: [
      { question_text: 'Which country allows completely tax-free crypto gains if the crypto is held for more than one year?', explanation: 'Germany offers one of the most favorable crypto tax rules in the world — crypto held for more than 12 months is sold completely tax-free. This has attracted many European crypto investors to hold rather than trade.', options: [{ option_text: 'Germany — crypto held 12+ months is completely tax-free', is_correct: true }, { option_text: 'USA — the long-term capital gains rate is 0% for all taxpayers', is_correct: false }, { option_text: 'UK — crypto is always tax-free for individual investors', is_correct: false }, { option_text: 'Singapore — no taxes of any kind on crypto', is_correct: false }] },
      { question_text: 'What is the US gift tax EXCLUSION for crypto gifts in 2024?', explanation: 'The annual gift exclusion is $18,000 per person in 2024. You can give up to $18,000 of crypto to any individual without triggering gift tax. The recipient inherits your cost basis and must pay capital gains when they sell.', options: [{ option_text: '$18,000 per person — gifts up to this amount are not taxed', is_correct: true }, { option_text: '$10,000 per person — the FBAR reporting threshold also applies to gifts', is_correct: false }, { option_text: 'Unlimited — crypto gifts are always tax-free', is_correct: false }, { option_text: '$1,000 per year — gifts above this amount must be reported', is_correct: false }] },
      { question_text: 'Why is donating APPRECIATED CRYPTO directly to charity more tax-efficient than selling it and donating cash?', explanation: 'When you donate crypto directly, you get a deduction for the full market value AND avoid paying capital gains tax on the appreciation. If you sold first, you\'d pay capital gains tax on the profit, then donate the after-tax amount. The charity gets the same benefit either way.', options: [{ option_text: 'You deduct full market value AND pay no capital gains on the appreciation — double benefit', is_correct: true }, { option_text: 'Crypto donations are deductible at 150% of market value — a bonus for crypto donors', is_correct: false }, { option_text: 'Donating crypto triggers a tax credit (not just deduction) equal to 30% of the donation', is_correct: false }, { option_text: 'Selling first is actually better — you get a cash deduction which is simpler', is_correct: false }] },
      { question_text: 'What is a STEPPED-UP BASIS for inherited crypto?', explanation: 'When you inherit crypto, its cost basis "steps up" to the fair market value on the date the previous owner died — eliminating all the capital gains that accrued during their lifetime. If grandpa bought Bitcoin at $1,000 and it\'s worth $80,000 when he dies, your basis is $80,000 — not $1,000.', options: [{ option_text: 'The cost basis resets to fair market value at the date of death — eliminating prior gains', is_correct: true }, { option_text: 'The basis doubles from the deceased\'s original cost basis', is_correct: false }, { option_text: 'The basis increases by the inflation rate from the original purchase date', is_correct: false }, { option_text: 'Inherited crypto has a basis of zero — estate taxes cover the full gain', is_correct: false }] },
      { question_text: 'What does FBAR stand for and when is it required?', explanation: 'FBAR stands for Report of Foreign Bank and Financial Accounts (FinCEN Form 114). US citizens must file it if they have foreign financial accounts with a combined value exceeding $10,000 at any point during the year.', options: [{ option_text: 'Report of Foreign Bank and Financial Accounts — required when foreign accounts exceed $10,000', is_correct: true }, { option_text: 'Federal Bitcoin and Asset Report — required when Bitcoin gains exceed $10,000', is_correct: false }, { option_text: 'Foreign Blockchain Activity Report — required for DEX users with foreign transactions', is_correct: false }, { option_text: 'Financial Base Asset Report — required when your portfolio exceeds $10,000', is_correct: false }] },
      { question_text: 'What is the single most important piece of advice for anyone with complex crypto taxes?', explanation: 'Crypto tax law is evolving rapidly and complex situations (DeFi, NFTs, international accounts, mining businesses) have nuanced treatment. A qualified CPA or tax attorney who specializes in crypto can save far more in taxes than they charge in fees — and prevent costly mistakes.', options: [{ option_text: 'Consult a qualified tax professional who specializes in cryptocurrency', is_correct: true }, { option_text: 'Use whichever tax software is cheapest — they all give the same result', is_correct: false }, { option_text: 'Report all crypto as long-term gains regardless of holding period — it\'s the safest approach', is_correct: false }, { option_text: 'Only report transactions that exchanges sent you a 1099 for', is_correct: false }] },
      { question_text: 'A US citizen uses a non-US crypto exchange. Should they be aware of FBAR or FATCA requirements?', explanation: 'YES. US citizens must report foreign financial accounts exceeding $10,000 in aggregate. The IRS has been working to include foreign crypto exchange accounts in these requirements. Any non-US exchange holding above this threshold warrants consulting a tax professional.', options: [{ option_text: 'Yes — foreign crypto accounts may fall under FBAR and FATCA reporting requirements', is_correct: true }, { option_text: 'No — FBAR only applies to traditional bank accounts, not crypto exchanges', is_correct: false }, { option_text: 'No — as long as the exchange is licensed in its home country, no US reporting is required', is_correct: false }, { option_text: 'Only if the exchange is based in a country with a US tax treaty', is_correct: false }] },
    ],
  },

];

// ─────────────────────────────────────────────────────────
// SEED HANDLER
// ─────────────────────────────────────────────────────────
export async function POST(request) {
  try {
    const session = await getServerSession(authOptions);
    if (session?.user?.email?.toLowerCase() !== TEACHER_EMAIL?.toLowerCase()) {
      return Response.json({ error: 'Teacher only' }, { status: 403 });
    }
    await db.rpc('run_sql', { query: "ALTER TABLE learn_lessons ADD COLUMN IF NOT EXISTS emoji TEXT DEFAULT '📚'" }).then(() => {}, () => {});
    const { classId } = await request.json().catch(() => ({}));
    let moduleId;
    const { data: existingMod } = await db.from('learn_modules').select('id').eq('title', MODULE.title).limit(1).single();
    if (existingMod) {
      moduleId = existingMod.id;
    } else {
      const { data: newMod, error: modErr } = await db.from('learn_modules').insert({ title: MODULE.title, emoji: MODULE.emoji, description: MODULE.description, order_index: MODULE.order_index, class_id: classId || null, is_published: true }).select('id').single();
      if (modErr) return Response.json({ error: `Module create failed: ${modErr.message}` }, { status: 500 });
      moduleId = newMod.id;
    }
    const results = [];
    for (const lesson of LESSONS) {
      const { data: existingLesson } = await db.from('learn_lessons').select('id').eq('module_id', moduleId).eq('title', lesson.title).limit(1).single();
      let lessonId, wasUpdate = false;
      if (existingLesson) {
        lessonId = existingLesson.id; wasUpdate = true;
        await db.from('learn_lessons').update({ emoji: lesson.emoji, description: lesson.description, order_index: lesson.order_index, tokens_reward: lesson.tokens_reward, pass_threshold: lesson.pass_threshold }).eq('id', lessonId);
        await db.from('learn_blocks').delete().eq('lesson_id', lessonId);
        const { data: oldQs } = await db.from('learn_questions').select('id').eq('lesson_id', lessonId);
        const oldQIds = (oldQs || []).map(q => q.id);
        if (oldQIds.length) await db.from('learn_options').delete().in('question_id', oldQIds);
        await db.from('learn_questions').delete().eq('lesson_id', lessonId);
      } else {
        const { data: newLesson, error: lessonErr } = await db.from('learn_lessons').insert({ module_id: moduleId, title: lesson.title, emoji: lesson.emoji, description: lesson.description, order_index: lesson.order_index, tokens_reward: lesson.tokens_reward, pass_threshold: lesson.pass_threshold, questions_to_show: 5, is_published: true, ai_tutor_enabled: true }).select('id').single();
        if (lessonErr) { results.push({ lesson: lesson.title, status: 'error', error: lessonErr.message }); continue; }
        lessonId = newLesson.id;
      }
      await db.from('learn_blocks').insert(lesson.blocks.map((b, i) => ({ lesson_id: lessonId, block_type: b.block_type, content: b.content, order_index: i + 1 })));
      for (let qi = 0; qi < lesson.questions.length; qi++) {
        const q = lesson.questions[qi];
        const { data: newQ } = await db.from('learn_questions').insert({ lesson_id: lessonId, question_text: q.question_text, explanation: q.explanation, order_index: qi + 1 }).select('id').single();
        if (newQ) await db.from('learn_options').insert(q.options.map((o, oi) => ({ question_id: newQ.id, option_text: o.option_text, is_correct: o.is_correct, order_index: oi + 1 })));
      }
      results.push({ lesson: lesson.title, status: wasUpdate ? 'updated' : 'created', id: lessonId });
    }
    return Response.json({ success: true, moduleId, moduleName: MODULE.title, results, created: results.filter(r => r.status === 'created').length, updated: results.filter(r => r.status === 'updated').length, errors: results.filter(r => r.status === 'error').length });
  } catch (err) {
    return Response.json({ error: `Unexpected error: ${err.message}` }, { status: 500 });
  }
}

export async function GET() {
  return Response.json({ info: 'POST to seed the Crypto & Taxes module.', lessons: LESSONS.map(l => `${l.emoji} ${l.title}`) });
}
